# files to compile
OBJS = TestMove.cpp libs/sdl2_rc.cpp
# compiler
CC = g++
# compilation options
#COMPILER_FLAGS = 
# libraries to link
LINKER_FLAGS = -lSDL2 -lSDL2_image
# executable name
OBJ_NAME = TestMove.exe

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
