# files to compile
OBJS = window_pop.cpp libs/sdl_op.cpp
# compiler
CC = g++
# compilation options
#COMPILER_FLAGS = 
# libraries to link
LINKER_FLAGS = -lSDL2
# executable name
OBJ_NAME = window_pop.exe

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
